language: python
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test
services:
- postgresql
branches:
  only: final
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python create_db_only.py
script:
- coverage run --source=app tests.py
after_success:
- coverage report
deploy:
  provider: heroku
  api_key:
    secure: mRsFUtxzrBdhUncHbjSu3ThZya/8312WUZMsrp6aaasze42UnruqFc4KyY8UNqv5NGWnzjCEmfLmEa1u8ZeVmZqW8ecC5lcxVUGSbSDwwscFHiTbQAYdk6wZne+QTzwIdoZz5mvUqEXCzn1XuxPagV+IBNXBn/Xe2Ko9cztXyqKVjLjxn4/ZJ8F4RD7SHQtsW9TTT/B9F+T/3t8FGZS7HkCwG1dh2Ijz9910V8TiX3z+Wdylm37HC8OzEm8kBOs9I2boWnyIjhCG94orubYpuMX91SuFV08aKKjs8eHcfiK+7RS4zT5g93ZG/AZ+rmu/UcmWbAkn2YoNtfhs5dEiCrpCOikvrT67qK0qWk+07xZJsI+BGd5gzMj4Y+n79NeD43rYcfLpyHOHGYnuHV7p7uYLgXrhcQk+Jh5Yo0HVxLJRt5f+iEj7vlohgIKLrRdv1PzjP6DaaL4h4xnWd20Fii6c+jVzAM/MexCgZlFFZGR2FHbDlHC16f+3xaLzedqcALPlKcv2SEq4O1gz9iOLxNFnLDt2+lfmtLQVcAumZo37lGaLnfyNpb0ZMJNgxUjLmyp0lKq0ZFklGFBXI8YbYrhSRFc8GVRlNdGzqK18ALO9kg7TF95MeCAybPud353NNYb8w5DPaV6UkxGAxfAgQWBjo1KkGR0YxK7l4JtVbjI=
  app: teamaltair2017
  on:
    repo: lottechan/jackal-flask
    branch: final
